name: Bug Report
description: Report a bug in Git Worktree Manager
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Open a project with multiple worktrees
        2. Click ...
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: input
    id: ide-version
    attributes:
      label: IDE & Version
      placeholder: "IntelliJ IDEA 2025.1.1"
    validations:
      required: true
  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      placeholder: "0.1.0"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "macOS 15, Ubuntu 24.04, Windows 11"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Paste from Help > Show Log in Explorer/Finder
      render: shell
